apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        qcloud-app: election-demo
      name: election-demo
      namespace: demo
    spec:
      ports:
      - name: tcp7001
        protocol: TCP
        port: 7001
        targetPort: 7001 
      selector:
        qcloud-app: election-demo
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        description: election-demo
      labels:
        qcloud-app: election-demo
      name: election-demo
      namespace: demo
    spec:
      minReadySeconds: 1
      replicas: 1
      revisionHistoryLimit: 3
      selector:
        matchLabels:
          qcloud-app: election-demo
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        type: RollingUpdate
      template:
        metadata:
          labels:
            qcloud-app: election-demo
        spec:
          containers:
            - image: xxx.com/election-demo:0.0.1
              env:
                - name: EGG_SERVER_ENV
                  value: demo
                - name: EGG_WORKERS
                  value: "2"
              imagePullPolicy: IfNotPresent
              name: election-demo
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthCheck
                  port: 7001
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 2
              ports:
                - containerPort: 7001
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthCheck
                  port: 7001
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 2
                timeoutSeconds: 2
              securityContext:
                allowPrivilegeEscalation: true
                privileged: true
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "500m"
                limits:
                  memory: "512Mi"
                  cpu: "1000m"
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: xxx
          - name: xxx
          restartPolicy: Always
          securityContext: {}
          serviceAccountName: ""
          terminationGracePeriodSeconds: 30
          volumes: null