apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        qcloud-app: election-demo
      name: election-demo
      namespace: server-universal
    spec:
      ports:
      - nodePort: 31540
        name: tcp7001
        protocol: TCP
        port: 7001
        targetPort: 7001 
      selector:
        qcloud-app: election-demo
      sessionAffinity: None
      type: NodePort
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        description: election-demo
      labels:
        qcloud-app: election-demo
      name: election-demo
      namespace: server-universal
    spec:
      minReadySeconds: 10
      replicas: 1
      revisionHistoryLimit: 5
      selector:
        matchLabels:
          qcloud-app: election-demo
      strategy:
        rollingUpdate:
          maxSurge: 1
          maxUnavailable: 0
        type: RollingUpdate
      template:
        metadata:
          labels:
            qcloud-app: election-demo
        spec:
          containers:
            - image: ccr.ccs.tencentyun.com/quqi/election-demo:0.0.16
              env:
                - name: EGG_SERVER_ENV
                  value: prod
                - name: EGG_WORKERS
                  value: "4"
              imagePullPolicy: IfNotPresent
              name: election-demo
              livenessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthCheck
                  port: 7001
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 1
                timeoutSeconds: 2
              ports:
                - containerPort: 7001
                  protocol: TCP
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  path: /healthCheck
                  port: 7001
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 5
                successThreshold: 2
                timeoutSeconds: 2
              securityContext:
                allowPrivilegeEscalation: true
                privileged: true
                readOnlyRootFilesystem: false
                runAsNonRoot: false
              stdin: true
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              tty: true
              resources:
                requests:
                  memory: "512Mi"
                  cpu: "1000m"
                limits:
                  memory: "1024Mi"
                  cpu: "2000m"
          dnsPolicy: ClusterFirst
          imagePullSecrets:
          - name: qcloudregistrykey
          - name: tencenthubkey
          restartPolicy: Always
          securityContext: {}
          serviceAccountName: ""
          terminationGracePeriodSeconds: 30
          volumes: null